### 获取随机值nonce
GET {{host}}/api/user/gen-nonce?walletAddress={{walletAddress}}
Content-Type: application/json

### 使用签名进行登录
POST {{host}}/api/user/login
Content-Type: application/json

{
  "walletAddress": "{{walletAddress}}",
  "signature": "0x0bce4a754eb8651b2f1613c1ea9f3cd6523696b4e9f44e93d2ef58bd508e6cef6e5a4158cf2c1d91da8b467e4ccd2a0e5a57b745bcfa8c3516c8c9b7e43ee00e1b"
}

### 更新用户的等级
POST {{host}}/api/user/upgrade-level
Content-Type: application/json
Authorization: {{accessToken}}

{
  "level": 2
}

### 获取用户详情
GET {{host}}/api/user/detail
Content-Type: application/json
Authorization: {{accessToken}}

### 上传文件jpg
POST {{host}}/api/material/upload?materialType=1
Authorization: {{accessToken}}
Cache-Control: no-cache
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="20220223-161039-1.jpg"

< /Users/wangjunpeng/Downloads/20220223-161039-1.jpg
--WebAppBoundary--

### 上传文件video
POST {{host}}/api/material/upload?materialType=0
Authorization: {{accessToken}}
Cache-Control: no-cache
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="飞书20221102-163411.mp4"

< /Users/wangjunpeng/Downloads/飞书20221102-163411.mp4
--WebAppBoundary--

### 上传文件图片
POST {{host}}/api/material/upload?materialType=0
Authorization: {{accessToken}}
Cache-Control: no-cache
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="20220223-161039-1.jpg"

< /Users/wangjunpeng/Downloads/20220223-161039-1.jpg
--WebAppBoundary--

### 我的钱包详情
GET {{host}}/api/wallet
Content-Type: application/json
Authorization: {{accessToken}}

### hit单价
GET {{host}}/api/wallet/price-of-hit
Content-Type: application/json
Authorization: {{accessToken}}

### 发布视频
POST {{host}}/api/content/release
Content-Type: application/json
Authorization: {{accessToken}}

{
  "coverImg": "image/1c80e16dbc2d483a8a48edbceafc93a4.jpg",
  "videoFilename": "video/88680d29e6a04c8f937546e8b2e90c63.mp4",
  "title": "title",
  "description": "descri",
  "watchLevel": 0,
  "enabledIpNft": true,
  "countIpNft": 100,
  "priceIpNft": 20,
  "ipNftRatioForInvestor": 0.8,
  "maxCountIpNftForPerInvestor": 10,
  "yieldRateOfInfluencer": 0.3,
  "yieldRateOfViewer": 0.3,
  "amountHit": 0
}

### 视频详情
GET {{host}}/api/content/detail?contentId=5
Content-Type: application/json
Authorization: {{accessToken}}


### 我赞过的视频
GET {{host}}/api/content/page-content-by-liked?pageSize=20&pageNo=1
Content-Type: application/json
Authorization: {{accessToken}}

### 根据用户等级查询视频
GET {{host}}/api/content/page-content-by-level
Content-Type: application/json
Authorization: {{accessToken}}

### 点赞视频
POST {{host}}/api/content/like
Content-Type: application/json
Authorization: {{accessToken}}

{
  "contentId": 1
}

### 可投资的视频
GET {{host}}/api/content/page-content-by-stocking
Content-Type: application/json
Authorization: {{accessToken}}

### xieshuai使用签名进行登录
POST {{host}}/api/user/login
Content-Type: application/json

{
  "walletAddress": "0xbe2f17ae0f50bded34e952226c8afceaf9b718a2",
  "message": "Welcome to HitPot!\n\nClick to sign in and accept the HitPot Terms of Service.\n\nThis request will not trigger a blockchain transaction or cost any gas fees.\n\nWallet address:\n0xbe2f17ae0f50bded34e952226c8afceaf9b718a2\n\nNonce:\nTH2QirA3fbrR2ICgoK-Qz",
  "signature": "0x11cb9771c5146b9bfe92eba1d9dfdb087cfe1828ed78fd123313c390663b09da49624b93446ffe31e5d97686343869170ddbf561304cc32c148787ebc1b78ab21c"
}

### 使用签名进行登录2
POST {{host}}/api/user/login
Content-Type: application/json

{
  "walletAddress": "0x3aF605Ec533EF13Cff525C92cCaD8608C58ad42E",
  "message": "Example `personal_sign` message",
  "signature": "0x13db60762754c6b26f49b8a58f032aeb83e5aea5bba72b2175fdf7ea67ab7cad2a8b4ac48e33c2b29e7527684a27a5e6ba6c46f565ef24f2dd0dbfe982acdb691b"
}

### 获取用户详情
GET {{host}}/api/user/detail
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOiIweGJlMmYxN2FlMGY1MGJkZWQzNGU5NTIyMjZjOGFmY2VhZjliNzE4YTIiLCJkZXZpY2UiOiJkZWZhdWx0LWRldmljZSIsImVmZiI6MTY4MDQyNjI2MTUxOSwicm5TdHIiOiJMSmhRaDY0T1g5RUtta014RUdPNG9uQlFOT2xBWkI2MCJ9.COAtXkGDejQRgsFD-vXVXhQLEvVCl8a0YhTqjYIcIYk


### 获取hit单价
GET {{host}}/api/wallet/price-of-hit
Content-Type: application/json
Authorization: {{accessToken}}


### 兑换hit
POST {{host}}/api/wallet/exchange-hit
Content-Type: application/json
Authorization: {{accessToken}}

{
  "amountHit": 50,
  "priceHit": 0.02
}


### 提现
POST {{host}}/api/wallet/withdraw
Content-Type: application/json
Authorization: {{accessToken}}

{
  "amountPot": 1
}


### 首页推荐
GET {{host}}/api/content/list-most-popular-content
Content-Type: application/json
Authorization: {{accessToken}}


### 观看视频
POST {{host}}/api/content/watch
Content-Type: application/json
Authorization: {{accessToken}}

{
  "contentId": 5,
  "duration": 60
}

### 向视频中充值hit
POST {{host}}/api/wallet/deposit-to-content
Content-Type: application/json
Authorization: {{accessToken}}

{
  "adLink": "https://www.baidu.com",
  "adTitle": "百度",
  "amountHit": 100,
  "contentId": 5
}

### 购买NFT
POST {{host}}/api/wallet/purchase-content-nft
Content-Type: application/json
Authorization: {{accessToken}}

{
  "amountPot": 141,
  "contentId": 9,
  "count": 7
}

### 订阅创作者
POST {{host}}/api/user/subscribe
Content-Type: application/json
Authorization: {{accessToken}}

{
  "creatorId": "0x3af605ec533ef13cff525c92ccad8608c58ad42e"
}

### 检查我是否订阅过该作者
POST {{host}}/api/user/subscribe/check
Content-Type: application/json
Authorization: {{accessToken}}

{
  "creatorId": ["0x3af605ec533ef13cff525c92ccad8608c58ad42e"]
}

### 获取我订阅的作者动态
GET {{host}}/api/content/page-content-by-subscribe
Content-Type: application/json
Authorization: {{accessToken}}


### 获取pot
POST {{host}}/api/wallet/faucet
Content-Type: application/json

{
  "address": "0xC5aAEa1eE7683488A26e5990c0Be78FB803109c3",
  "amount": 100
}
