server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  jwt-secret-key: hitpot
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  is-log: false
  token-name: Authorization

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hitpot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root$%^
    hikari: # https://github.com/brettwooldridge/HikariCP (uses milliseconds for all time values)
      maximumPoolSize: 20
      minimumIdle: 10
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
      connection-test-query: select 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  redis:
    host: 127.0.0.1
    port: 6379
    client-type: jedis
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

  web:
    resources:
      cache:
        period: 0

  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB

material:
  upload:
    saveDir: /tmp
  baseUrl: "/"
  ffmpeg_command: "/usr/local/bin/ffmpeg"

blockchain:
  server: http://poa-rpc.bestchain.fun:8545
  chain_id: 20230131
  private_key: fecd8a9c9eb1a4c5b51df0c4ed1b2325358797168c5cfcbe46d97237c1247706
  total_hit_for_per_hour: 1000000000
  price_of_hit: 20000
  contract:
    hitpot_bridage_address: "0x476f1dd0f60733Ee51c6704d0691E8F732D96102"
    pot_token_address: "0x9EB183F819a407bB70810035807590DBaa8ae9Be"
