spring:
  datasource:
    url: jdbc:mysql://mysql.mysql:3306/hitpot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: RRim0JyBGezM2jl2
  redis:
    host: redis.redis
    port: 6379

material:
  upload:
    saveDir: /ts-hitpot-server/upload
  baseUrl: /static/
